name: Update html code in readme
on: push
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run jinja2-cli[yaml] -o README.md README.md.j2 data.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          author_name: "SSC Render Bot"
          author_email: "ssc@iwr.uni-heidelberg.de"
          message: "Update html code in README.md"
